Capstone/src/main/java/com/techelevator/model/Survey.java
package com.techelevator.model;

import java.util.Arrays;
import java.util.List;

import javax.validation.constraints.AssertTrue;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import org.springframework.beans.factory.annotation.Autowired;


public class Survey {

	
	private static final List<String> ACTIVITY_LEVELS = Arrays.asList(
			new String[] {"Inactive", "Sedentary", "Active", "Extremely Active"});
	
	private static final List<String> STATES = Arrays.asList(
			new String[] {"AL","AK","AZ","AR","CA","CO","CT","DE","DC","FL",
					  "GA","HI","ID","IL","IN","IA","KS","KY","LA","ME",
				      "MD","MA","MI","MN","MS","MO","MT","NE","NV","NH",
				      "NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI",
				      "SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"});
	
	
	private String parkCode;

	@NotBlank
	private String parkName;
	
	@NotBlank
	@Email
	private String email;
	


	@NotBlank
	private String residenceState;
	
	@AssertTrue
	public boolean isStateValid() {
		return getStateList().contains(residenceState);
	}
	public List<String> getStateList() {
		return STATES;
	}
	
	@NotBlank
	private String activityLevel;
	
	@AssertTrue
	public boolean isActivityLevelValid() {
		return getActivityLevelList().contains(activityLevel);
	}
	public List<String> getActivityLevelList() {
		return ACTIVITY_LEVELS;
	}

	public String getParkCode() {
		return parkCode;
	}

	public void setParkCode(String parkCode) {
		this.parkCode = parkCode;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getResidenceState() {
		return residenceState;
	}

	public void setResidenceState(String residenceState) {
		this.residenceState = residenceState;
	}
	
	public String getActivityLevel() {
		return activityLevel;
	}
	
	public void setActivityLevel(String activityLevel) {
		this.activityLevel = activityLevel;
	}
	
	public String getParkName() {
		return parkName;
	}
	public void setParkName(String parkName) {
		this.parkName = parkName;
	}

}

Capstone/src/main/java/com/techelevator/controller/homeController.java
package com.techelevator.controller;

import java.util.LinkedHashMap;
import java.util.Map;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import com.techelevator.model.Park;
import com.techelevator.model.ParkDAO;
import com.techelevator.model.Survey;
import com.techelevator.model.SurveyDAO;
import com.techelevator.model.WeatherDAO;

@Controller
public class homeController {
	
	@Autowired
	ParkDAO parkDAO;
	@Autowired
	WeatherDAO weatherDAO;
	@Autowired
	SurveyDAO surveyDAO;
	
	/**
	 * GET - provides a list of all Park objects in the database to the home page
	 */
	@RequestMapping(method=RequestMethod.GET, path={"/", "/home"})
    public String homePage(ModelMap modelMap) {
		modelMap.put("parks", parkDAO.getAllParks());
        return "home";
    }
	
	/**
	 * GET - provides a Park object to the parkDetail page based on the park that was clicked,
	 * 	          along with a single Weather object for the chosen park on day 1
	 * 
	 * @param String code - received as a query string in order to provide the Park object
	 * @param HttpSession session - to keep track of the temperature preference across pages
	 */
	@RequestMapping(method=RequestMethod.GET, path= "/parkDetail")
	public String detailPage(ModelMap modelMap, @RequestParam String code, HttpSession session) {
		Park p = parkDAO.getParkByCode(code);
		modelMap.put("park", p);
		
		// if user hasn't yet selected a temperature preference, set to Fahrenheit by default
		if(session.getAttribute("tempPreference")== null) {
			session.setAttribute("tempPreference", "Fahrenheit");  //make boolean, such as prefersFahrenheit
		}
		String tempPref = (String)session.getAttribute("tempPreference");
		// single Weather object for day 1 (aka today) with the temperature values set by tempPref
		modelMap.put("weatherForToday", weatherDAO.getWeatherForToday(code, tempPref));  
		
		return "parkDetail";
	}
	
	/**
	 * POST - handles the change in temperature preference when form is submitted from the parkDetail page
	 * 
	 * @param String tempPreference - either Celsius or Fahrenheit
	 * @param String hiddenParkCode - for RedirectAttributes
	 * @param RedirectAttributes ra - for passing parkCode to the parkDetail GET redirect
	 * @param HttpSession session - to keep track of the temperature preference across pages
	 */
	@RequestMapping(method=RequestMethod.POST, path="/parkDetail")
	public String temperatureToggle(ModelMap modelMap, @RequestParam String tempPreference, 
																@RequestParam String hiddenParkCode, RedirectAttributes ra, HttpSession session) {
		session.setAttribute("tempPreference", tempPreference);
		ra.addAttribute("code", hiddenParkCode);
		return "redirect:/parkDetail";
	}
	
	/**
	 * GET - provides a map of 5 Weather objects and corresponding recommendations for the selected park
	 * 
	 * @param String code - received as a query string in order to provide the Park object
	 * @param HttpSession session - to keep track of the temperature preference across pages
	 */
	@RequestMapping(method=RequestMethod.GET, path="/weatherDetail")
	public String weatherDetailPage(ModelMap modelMap, @RequestParam String code, HttpSession session) {

		// if user hasn't yet selected a temperature preference, set to Fahrenheit by default
		if(session.getAttribute("tempPreference")== null) {
			session.setAttribute("tempPreference", "Fahrenheit"); //separate method to handle default preference
		}
		String tempPref = (String)session.getAttribute("tempPreference");
		// Map of Five Weather objects and String recommendation for the extended forecast with the temperature values set by tempPref
		modelMap.put("weatherMap", weatherDAO.getWeatherByParkCode(code, tempPref));
		return "weatherDetail";
	}
	
	/**
	 * GET - survey form to select a favorite park
	 */
	@RequestMapping(method=RequestMethod.GET, path="/survey")
	public String surveyPage(ModelMap modelMap) {
		// for validation rules in the POST method
        if( ! modelMap.containsAttribute("survey")){
        	modelMap.put("survey", new Survey());
        	modelMap.put("parkNamesList", parkDAO.getAllParkNames());  // to provide dropdown of Park Names
        }
        return "survey";
	}
	
	/**
	 * POST - survey form to select a favorite park
	 * 
	 * @param Survey survey - contains user's form entries in order to add to database
	 */
	 @RequestMapping(path="/survey", method=RequestMethod.POST)
	    public String submitSurvey( @Valid @ModelAttribute("survey") Survey survey,
													        BindingResult result, RedirectAttributes flash) {
		 	// form validation 
	        if(result.hasErrors()) {
	            flash.addFlashAttribute("survey", survey);
	            flash.addFlashAttribute(BindingResult.MODEL_KEY_PREFIX + "survey", result);
	            flash.addFlashAttribute("message", "Please fix the following errors:");
	             return "redirect:/survey";
	        }
	        // if no form errors:
	        // translate parkName from form into parkCode required for Survey, then add to database
	        survey.setParkCode(parkDAO.getCodeByParkName(survey.getParkName()));
	        surveyDAO.saveSurvey(survey);
	        return "redirect:/favoriteParks";
	    }
	 
	 /**
	 * GET - Provides a map of Park objects with the number of surveys for that park
	 */
	 @RequestMapping(path="/favoriteParks", method=RequestMethod.GET)
	 public String showFavoriteParks(ModelMap modelMap) {
		 	// map of parkNames with the count of surveys for each
	        Map<String, Integer> currentSurveys = surveyDAO.getAllParkRankings();  //change to map of parks to surveynum
	        
	        // translate map of parkNames and counts to map of Park objects and counts
	        // so that the favoriteParks page will have each park name, count of surveys,
	        // and the park code in order to link to park image ('parkCode.jpg')
	        Map<Park, Integer> surveyParks = new LinkedHashMap<>();
	        for(String s : currentSurveys.keySet()) {
	        	Park p = parkDAO.getParkByParkName(s);
	        	Integer count = currentSurveys.get(s);
	        	surveyParks.put(p, count);
	        }
	        modelMap.put("surveyParks", surveyParks);
		 
		 return "favoriteParks";
	 }
	
	
}

Capstone/src/main/webapp/WEB-INF/jsp/favoriteParks.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<c:import url="/WEB-INF/jsp/common/header.jsp" />
	<%-- header.jsp includes the NPGeek logo and navigation links --%>

<%-- The main content displays tiles for each park that has received
	 at least 1 vote.
	 Each tile includes the park image, park name and number of votes. --%>

<div class="main-content">
	<div class="favorites">
		
		<h1>Current Ranking of Parks!</h1>
		<c:url var="surveyLink" value="/survey" />
		<p>Click <a href="${surveyLink}">here</a> to submit your favorite!</p>
		
			<div>
			
			<c:forEach var="parkAndCount" items="${surveyParks}">
				<div class="favoriteParks">
					<c:set var="parkItem" value="${parkAndCount.key}"/>
					<c:set var="ranking" value="${parkAndCount.value}"/>
					<c:url value="/parkDetail" var="parkDetailLink">
						<c:param name="code" value="${parkItem.code}"/>
					</c:url>
					
					<div class="fave-park-image">
						<c:url var="rankingImgUrl" value="/img/parks/${parkItem.code}.jpg"/>
						<a href="${parkDetailLink}"><img src="${rankingImgUrl}"/></a>
					</div>
					<div class="park-rank-info">
						<h1><a href ="${parkDetailLink}">${parkItem.name}</a></h1>
						<p>Number of Votes: ${ranking}</p>
					</div>
				</div>
			</c:forEach>
		</div>
	</div>
</div>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />

Capstone/src/main/webapp/WEB-INF/jsp/home.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<%-- --%>

<c:import url="/WEB-INF/jsp/common/header.jsp" />  
	<%-- header.jsp includes the NPGeek logo and navigation links --%>

<%-- The main content displays tiles for each park in the database.
	 Each tile includes the park image one the left, and on the right
	 is the park name, state, and description. --%>

	<div class="main-content">
	
		<c:forEach var="park" items="${parks}">
			<%-- ${parks} passed from homePage() in homeController --%>
			
			<div class="all-park-info">
			
				<c:url value="/parkDetail" var="parkDetailLink">
					<c:param name="code" value="${park.code}"/> 
				</c:url>
				<c:url value="/img/parks/${park.code}.jpg" var="parkImgUrl" />
					<%-- park images are named by the 4 character park code --%>
				
				<div class="park-image">
					<a href ="${parkDetailLink}"> <%-- image links to /parkDetail?code=____--%>
					<img src="${parkImgUrl}" alt="park image" /></a>
				</div>
				<div class="park-info">
					<h1><a href ="${parkDetailLink}">${park.name}</a></h1>
						<%-- park name links to /parkDetail?code=____--%>
					<h2>${park.state}</h2>
					<p>${park.description}</p>
				</div>
			</div>
		</c:forEach>
	</div>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />

Capstone/src/main/webapp/WEB-INF/jsp/parkDetail.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/common/header.jsp" />
	<%-- header.jsp includes the NPGeek logo and navigation links --%>

<%-- The main content displays all of the details for the chosen park,
	 in the following order:
	 - inspirational quote & quote source 
	 - park image (large) 
	 - park name, state & description 
	 - park facts includes all remaining fields
	 
	 This page also pulls from the weather table to show the 
	 forecast and temperature values for day 1, along with a
	 button providing the option to switch temperatures between
	 Celsius and Fahrenheit.
	 
	 Finally, there is a link to the extended forecast weather page.
--%>
	 

<div class="main-content">
	<div class="core-park-details">
		<div class="quote">
			<div id="fancyQuote">
				${park.inspirationalQuote}
			</div>
			<div id="quoteGiver">
				${park.quoteSource}
			</div>
		</div>
	<div class="park-detail-container">
		<div class="parkDetail-coreInfo">
			<div class="park-image">
				<c:url value="/img/parks/${park.code}.jpg" var="parkImgUrl" />
				<img src="${parkImgUrl}" alt="park image" />
			</div>
			<div class="detail-park-info">
				<h2>${park.name}</h2>
				<h3>${park.state}</h3>
				<p>${park.description}</p>
			</div>
		</div>
		<div class="extras">
			<div id="park-facts">
				<h4>Park Facts:</h4>
				<ul>
					<li><span>Year Founded:</span> ${park.yearFounded}</li>
					<li><span>Annual Visitor Count:</span> ${park.annualVisitorCount}</li>
					<li><span>Park Entry Fee:</span> $${park.entryFee}</li>
					<li><span>Miles of Trail:</span> ${park.milesOfTrail}</li>
					<li><span>Number of Campsites:</span> ${park.numberOfCampsites}</li>
					<li><span>Climate:</span> ${park.climate}</li>
					<li><span>Acreage:</span> ${park.acreage}</li>
					<li><span>Elevation:</span> ${park.elevationInFeet} ft.</li>
					<li><span>Number of Animal Species:</span> ${park.numberOfAnimalSpecies}</li>
				</ul>
			</div>
			<div class="weather">
				<h3>Today's Weather:</h3>
			
				<div id="today-weather-image">
					<c:url var="weatherImgUrl" value="/img/weather/${weatherForToday.forecast}.png" />
					<img src="${weatherImgUrl}" alt="forecast image for ${weatherForToday.forecast}" />
				</div>
				<div>
					
					<div id="tempPreferenceForSession">
						<%-- This block gets the temperature preference from the controller in order show
							 the correct character (C or F) for the high and low temperatures, as well as to
							 choose which radio button to mark as "checked" by default in the form below. --%>		 
						<c:choose>
							<c:when test="${tempPreference.equals('Celsius')}">
								<c:set var="tempChar" value="C" />
								<c:set var="cSelected" value="checked" />
								<c:set var="fSelected" value="" />
							</c:when>
							<c:otherwise>
								<c:set var="tempChar" value="F" />
								<c:set var="cSelected" value="" />
								<c:set var="fSelected" value="checked" />
							</c:otherwise>
						</c:choose>						
					
						<span>High ${weatherForToday.highTemp}&deg${tempChar} | Low ${weatherForToday.lowTemp}&deg${tempChar}</span>
					
						<form action="parkDetail" method="POST">
							<label for=Fahrenheit>Fahrenheit:</label>
							<input type="radio" name="tempPreference" value="Fahrenheit" ${fSelected} />
							<label for=Celsius>Celsius:</label>
							<input type="radio" name="tempPreference" value="Celsius" ${cSelected} />
							<input type="hidden" id="hiddenParkCode" name="hiddenParkCode" value="${park.code}" />
							<p><button type="submit" class="btn btn-primary" id="tempButton">Change Temperature Preference</button></p>
						</form>
					</div>
						
				</div>
			</div>
		</div>
			<div id="five-day-forecast">
				<c:url value="/weatherDetail" var="weatherDetailLink">
					<c:param name="code" value="${park.code}" />
				</c:url>
					<h5><a href="${weatherDetailLink}">Five Day Forecast and Recommendations</a></h5>
			</div>
			
		</div>
	</div>
</div>


<c:import url="/WEB-INF/jsp/common/footer.jsp" />

Capstone/src/main/webapp/WEB-INF/jsp/survey.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<c:import url="/WEB-INF/jsp/common/header.jsp" />

<div class="survey-main-content">

	<h1>Favorite Park Survey</h1>
	<p>Fill out the details below to vote for your favorite park!</p>
	<div id="surveyForm">
		<c:url var="submitSurveyUrl" value="/survey" />
		<form:form modelAttribute="survey" action="${submitSurveyUrl}" method="POST">
			<div class="form-group">
				<label for="FavoriteNationalPark">Favorite National Park:</label>
				<form:select class="form-control" path="parkName">
					<form:options items="${parkNamesList}"/>
				</form:select>
			</div>
			<div class="form-group">
				<label for="email">Email:</label>
				<form:input type="email" class="form-control" path="email"/>
				<form:errors path="email" class="bg-danger"/>
			</div>
			<div class="form-group">
				<label for="state">State of Residence:</label>
				<form:select class="form-control" path="residenceState">
					<form:options items="${survey.stateList}"/>
				</form:select>
				<form:errors path="stateValid" />
			</div>
			<div class="form-group">
				<label for="activityLevel">Activity Level:</label>
				<form:select class="form-control" path="activityLevel">
					<form:options items="${survey.activityLevelList}"/>
				</form:select>
				<form:errors path="activityLevelValid" />
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form:form>
	</div>

</div>

<c:import url="/WEB-INF/jsp/common/footer.jsp" />

Capstone/src/main/webapp/WEB-INF/jsp/weatherDetail.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:import url="/WEB-INF/jsp/common/header.jsp" />

	
	<div class="weather-group">
	
		<c:forEach var="dailyWeather" items="${weatherMap}">
			
			<c:set var="weatherItem" value="${dailyWeather.key}"/>
			<c:set var="recommendations" value="${dailyWeather.value}"/>
	
			<div class="five-day-weather">
			<h5>Day ${weatherItem.forecastDayNumber}</h5>
				<div id="daily-weather-image">
					<c:url var="dailyWeatherImgUrl" value="/img/weather/${weatherItem.forecast}.png" />
					<img src="${dailyWeatherImgUrl}" alt="forecast image for ${weatherItem.forecast}" />
				</div>
				<div>
					<%-- This block gets the temperature preference from the controller in order show
							 the correct character (C or F) for the high and low temperatures. --%>		 
					<c:choose>
						<c:when test="${tempPreference.equals('Celsius')}">
							<c:set var="tempChar" value="C" />
						</c:when>
						<c:otherwise>
							<c:set var="tempChar" value="F" />
						</c:otherwise>
					</c:choose>						
					<span>High ${weatherItem.highTemp}&deg${tempChar} | Low ${weatherItem.lowTemp}&deg${tempChar}<br/></span>
				</div>
				<br/>
				<p class="recommendations">
					${recommendations}
				</p>
			</div>
		</c:forEach>
	</div>


<c:import url="/WEB-INF/jsp/common/footer.jsp" />